name: my first GH action workflow

on:
  push:
    branches:
      - main  # Fixed spacing issue

jobs:
  examplejob:
    runs-on: ubuntu-latest  # Fixed indentation and structure

    steps:
      - name: checkout code  # Fixed typo
        uses: actions/checkout@v3

      - name: exec cmd
        run: echo "Hello from shell"
