name: my first GH action workflow

on:
  push:
    branches:
      - main  

jobs:
  examplejob:
    runs-on: ubuntu-latest  

    steps:

      - name: exec cmd
        run: echo "Hello from GitHub Actions"
