name: envcheck
on:
    push: 
        branches:
            main

jobs:
    envcheck:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: printOS
              run: |
               cat /etc/os-release
            
            - name: date
              env:
                DATE_FMT: "+%Y-%m-%d %H:%M:%S"
              run: date "$DATE_FMT"
