name: envinfo

on:
  push:
    branches:
      - main

jobs:
  envinfo:
    runs-on: ubuntu-latest

    steps:
      - name: print current user and pwd
        run: |
          id
          pwd

      - name: print env variable
        shell: bash
        env:
          GREETING: Hello
        run: |
          echo "Greeting: $GREETING"
