name: envinfo

on:
  push:
    branches:
      - main

jobs:
  envinfo:
    runs-on: ubuntu-latest
    env:  # ✅ Define env here at the job level
      GREETING: Hello

    steps:
      - name: print current user and pwd
        run: |
          id
          pwd

      - name: env variable
        run: echo "Greeting: $GREETING"
