name: variables passing & matrix & condition
on:
  workflow_dispatch:

jobs:
  
  envvar_step_matrix:
    strategy:
      matrix:
        os: [20.04, 22.04]
    runs-on: ubuntu-${{ matrix.os }}

    env:
      MY_NAME: devopslearner
      MY_DAY: 10

    steps:
      
      - name: print two variables
        run: |
          echo "$MY_NAME on $MY_DAY"
          echo "RUNTIME_VAR = hello" >> $GITHUB_ENV

      - name: take runtimevar
        run: |
          echo "$RUNTIME_VAR"

      - name: Skip if skip.txt exists
        run: |
          if [ -f skip.txt ]; then
          echo "File exists, skipping step."
          exit 0
          fi
          echo "File not found, doing task..."
          # Your actual task here
        continue-on-error: true
