name: use secrets workflow
on: 
    push:
        branches:
            - main

jobs:
    sumapp:
        runs-on: ubuntu-latest
        steps:
            - name: chekout code
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: ${{secrets.PYTHON_VERSION}}

            - name: install dependencies
              run: python -m pip install --upgrade pip | pip install -r ./src/requirements.txt

            - name: exec code
              working-directory: ./src
              env:
                FLASK_APP: app.py
                FLASK_ENV: development
              run:
                flask run --host=0.0.0.0 --port=5000

            