name: pyapp&test
on: 
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    sumapp:
        runs-on: ubuntu-latest
        steps:
            - name: chekout code
              uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: ${{secrets.PYTHON_VERSION}}

            - name: install dependencies
              run: python -m pip install --upgrade pip | pip install -r ./src/requirements.txt

            - name: test
              run: pytest
          

            