name: file copy to required folder
on:
  # pull_request:
  #   types:
  #     - closed
  push:
    branches:
      - release

jobs:
  checkchanges:
    runs-on: self-hosted
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changes
        run: |
          git fetch origin
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'plugin'
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'plugin' || true)
          echo "changed_files=$CHANGED" >> "$GITHUB_OUTPUT"



